"""
Code Generator for SimpleUI Compiler
Generates Python/Turtle graphics code from AST
"""

import ast_nodes
from typing import List, TextIO


class CodeGenerator:
    """Generates executable Python code using Turtle graphics"""
    
    def __init__(self):
        self.indent_level = 0
        self.indent_size = 4
    
    def _indent(self) -> str:
        """Get current indentation string"""
        return ' ' * (self.indent_level * self.indent_size)
    
    def _hex_to_turtle_color(self, color: ast_nodes.Color) -> str:
        """Convert hex color to Turtle-compatible format"""
        # Turtle accepts hex colors directly
        return f'"{color.hex_value.lower()}"'
    
    def _generate_header(self) -> str:
        """Generate import statements and setup code"""
        return '''#!/usr/bin/env python3
"""
Generated by SimpleUI Compiler
This file contains Turtle graphics code to render the UI
"""

import turtle

# Setup turtle screen
screen = turtle.Screen()
screen.title("SimpleUI Output")
screen.setup(width=800, height=600)
screen.bgcolor("white")

# Create turtle for drawing
t = turtle.Turtle()
t.speed(0)  # Fastest drawing speed
t.hideturtle()

'''
    
    def _generate_rectangle(self, shape: ast_nodes.Shape, shape_id: int) -> str:
        """Generate code for drawing a rectangle"""
        code = f"\n{self._indent()}# Shape {shape_id}: Rectangle\n"
        
        # Move to position
        code += f"{self._indent()}t.penup()\n"
        code += f"{self._indent()}t.goto({shape.position.x}, -{shape.position.y})  # Note: Y inverted for Turtle\n"
        
        # Set colors
        code += f"{self._indent()}t.fillcolor({self._hex_to_turtle_color(shape.fill_color)})\n"
        code += f"{self._indent()}t.pencolor({self._hex_to_turtle_color(shape.outside_color)})\n"
        code += f"{self._indent()}t.pendown()\n"
        
        # Begin fill
        code += f"{self._indent()}t.begin_fill()\n"
        
        # Draw rectangle
        if shape.rounded:
            # Draw rounded rectangle (simplified: small circles at corners)
            radius = min(10, shape.size.width / 10, shape.size.height / 10)
            code += f"{self._indent()}# Drawing rounded rectangle\n"
            code += f"{self._indent()}for _ in range(2):\n"
            self.indent_level += 1
            code += f"{self._indent()}t.forward({shape.size.width})\n"
            code += f"{self._indent()}t.circle(-{radius}, 90)\n"
            code += f"{self._indent()}t.forward({shape.size.height})\n"
            code += f"{self._indent()}t.circle(-{radius}, 90)\n"
            self.indent_level -= 1
        else:
            # Draw regular rectangle
            code += f"{self._indent()}for _ in range(2):\n"
            self.indent_level += 1
            code += f"{self._indent()}t.forward({shape.size.width})\n"
            code += f"{self._indent()}t.left(90)\n"
            code += f"{self._indent()}t.forward({shape.size.height})\n"
            code += f"{self._indent()}t.left(90)\n"
            self.indent_level -= 1
        
        # End fill
        code += f"{self._indent()}t.end_fill()\n"
        
        return code
    
    def _generate_circle(self, shape: ast_nodes.Shape, shape_id: int) -> str:
        """Generate code for drawing a circle"""
        code = f"\n{self._indent()}# Shape {shape_id}: Circle\n"
        
        # Calculate radius (use minimum of width/height divided by 2)
        radius = min(shape.size.width, shape.size.height) / 2
        
        # Move to position (adjust for circle drawing from bottom)
        code += f"{self._indent()}t.penup()\n"
        code += f"{self._indent()}t.goto({shape.position.x + radius}, -{shape.position.y + radius})\n"
        
        # Set colors
        code += f"{self._indent()}t.fillcolor({self._hex_to_turtle_color(shape.fill_color)})\n"
        code += f"{self._indent()}t.pencolor({self._hex_to_turtle_color(shape.outside_color)})\n"
        code += f"{self._indent()}t.pendown()\n"
        
        # Draw circle
        code += f"{self._indent()}t.begin_fill()\n"
        code += f"{self._indent()}t.circle({radius})\n"
        code += f"{self._indent()}t.end_fill()\n"
        
        return code
    
    def _generate_line(self, shape: ast_nodes.Shape, shape_id: int) -> str:
        """Generate code for drawing a line"""
        code = f"\n{self._indent()}# Shape {shape_id}: Line\n"
        
        # Move to start position
        code += f"{self._indent()}t.penup()\n"
        code += f"{self._indent()}t.goto({shape.position.x}, -{shape.position.y})\n"
        
        # Set color
        code += f"{self._indent()}t.pencolor({self._hex_to_turtle_color(shape.outside_color)})\n"
        code += f"{self._indent()}t.pendown()\n"
        
        # Draw line (from position to position + width)
        code += f"{self._indent()}t.goto({shape.position.x + shape.size.width}, -{shape.position.y + shape.size.height})\n"
        
        return code
    
    def _generate_shape(self, shape: ast_nodes.Shape, shape_id: int) -> str:
        """Generate code for a single shape based on its type"""
        if shape.shape_type == 'rectangle':
            return self._generate_rectangle(shape, shape_id)
        elif shape.shape_type == 'circle':
            return self._generate_circle(shape, shape_id)
        elif shape.shape_type == 'line':
            return self._generate_line(shape, shape_id)
        else:
            raise ValueError(f"Unknown shape type: {shape.shape_type}")
    
    def _generate_footer(self) -> str:
        """Generate cleanup and exit code"""
        return f'''
{self._indent()}# Keep window open until clicked
{self._indent()}screen.exitonclick()
'''
    
    def generate(self, ast: ast_nodes.ShapeList) -> str:
        """
        Generate complete Python/Turtle code from AST
        
        Args:
            ast: ShapeList containing all shapes to render
            
        Returns:
            Complete Python code as string
        """
        code = self._generate_header()
        
        # Generate code for each shape
        # Remember: shapes are drawn in order, later shapes appear on top
        for i, shape in enumerate(ast.shapes, start=1):
            code += self._generate_shape(shape, i)
        
        code += self._generate_footer()
        
        return code
    
    def generate_to_file(self, ast: ast_nodes.ShapeList, output_file: str):
        """
        Generate code and write to file
        
        Args:
            ast: ShapeList to generate code from
            output_file: Path to output Python file
        """
        code = self.generate(ast)
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(code)
        
        print(f"Generated code written to: {output_file}")


# Convenience functions
def generate_code(ast: ast_nodes.ShapeList) -> str:
    """Generate Python/Turtle code from AST"""
    generator = CodeGenerator()
    return generator.generate(ast)


def generate_to_file(ast: ast_nodes.ShapeList, output_file: str):
    """Generate code and save to file"""
    generator = CodeGenerator()
    generator.generate_to_file(ast, output_file)


# Testing
if __name__ == "__main__":
    print("=== Code Generator Test ===")
    
    # Create test AST manually
    shapes = [
        ast_nodes.Shape(
            shape_type='rectangle',
            position=ast_nodes.Position(100, 50),
            size=ast_nodes.Size(200, 100),
            fill_color=ast_nodes.Color('#FF0000'),
            outside_color=ast_nodes.Color('#000000'),
            rounded=True
        ),
        ast_nodes.Shape(
            shape_type='circle',
            position=ast_nodes.Position(50, 150),
            size=ast_nodes.Size(80, 80),
            fill_color=ast_nodes.Color('#00FF00'),
            outside_color=ast_nodes.Color('#0000FF'),
            rounded=False
        ),
        ast_nodes.Shape(
            shape_type='line',
            position=ast_nodes.Position(0, 0),
            size=ast_nodes.Size(200, 200),
            fill_color=ast_nodes.Color('#000000'),
            outside_color=ast_nodes.Color('#FF00FF'),
            rounded=False
        )
    ]
    
    ast = ast_nodes.ShapeList(shapes=shapes)
    
    # Generate code
    generator = CodeGenerator()
    code = generator.generate(ast)
    
    print("Generated Python/Turtle Code:")
    print("=" * 60)
    print(code)
    print("=" * 60)
    
    # Optionally save to file
    output_file = "test_output.py"
    generator.generate_to_file(ast, output_file)
    print(f"\nCode also saved to {output_file}")
    print(f"Run it with: python {output_file}")