#!/usr/bin/env python3
"""
Generated by SimpleUI Compiler
This file contains Turtle graphics code to render the UI
"""

import turtle

# Setup turtle screen
screen = turtle.Screen()
screen.title("SimpleUI Output")
screen.setup(width=800, height=600)
screen.bgcolor("white")

# Create turtle for drawing
t = turtle.Turtle()
t.speed(0)  # Fastest drawing speed
t.hideturtle()


# Shape 1: Rectangle
t.penup()
t.goto(100, -50)  # Note: Y inverted for Turtle
t.fillcolor("#ff0000")
t.pencolor("#000000")
t.pendown()
t.begin_fill()
# Drawing rounded rectangle
for _ in range(2):
    t.forward(200)
    t.circle(-10, 90)
    t.forward(100)
    t.circle(-10, 90)
t.end_fill()

# Shape 2: Circle
t.penup()
t.goto(90.0, -190.0)
t.fillcolor("#00ff00")
t.pencolor("#0000ff")
t.pendown()
t.begin_fill()
t.circle(40.0)
t.end_fill()

# Shape 3: Line
t.penup()
t.goto(0, -0)
t.pencolor("#ff00ff")
t.pendown()
t.goto(200, -200)

# Keep window open until clicked
screen.exitonclick()
